aarch32/mpu: Don't call function with empty data array
It's a no-op if there are no regions passed and gcc 11 complains
that there might be an access to the array (which implies access to
uninitialized memory because its size is 0) in the
num_regions == 0 case.

Error message without this change:
error: 'arm_core_mpu_configure_dynamic_mpu_regions' reading 12 bytes
from a region of size 0

Signed-off-by: Patrick Georgi <pgeorgi@google.com>