include: zephyr: Fix minor issues from header file guard macros renaming
Script zephyr_header_guards.py was recently used to have more consistent
header file guards in include/zephyr/ file tree but some manual handmade
fixes are worth it.

Manually place header guards before the first #include directive in
include/zephyr/modem/ubx.h to prevent CI Compliance complains on lack
of documentation of the macro used as guard, as reported by the
error trace message below:
Error: define 'ZEPHYR_INCLUDE_MODEM_UBX_H_' is missing Doxygen comments.


Signed-off-by: Etienne Carriere <etienne.carriere@st.com>