Revert "arch: arm: userspace: minor refactor in z_arch_is_user_context"
This reverts commit 48fa076a56fdde42adcd572215f9fc85fb076c48.

That commit pulls in a header that causes the following failure on
many platforms/tests:

sanitycheck -p stm32f469i_disco -T tests/kernel/workq/work_queue_api

Building C object zephyr/CMakeFiles/offsets.dir/arch/arm/core/offsets/offsets.c.obj
In file included from /scratch/zephyr/zp1/zephyr/include/arch/arm/syscall.h:29,
                 from /scratch/zephyr/zp1/zephyr/include/arch/syscall.h:15,
                 from /scratch/zephyr/zp1/zephyr/include/syscall.h:12,
                 from /scratch/zephyr/zp1/zephyr/include/kernel_includes.h:32,
                 from /scratch/zephyr/zp1/zephyr/include/kernel.h:17,
                 from /scratch/zephyr/zp1/zephyr/kernel/include/kernel_structs.h:10,
                 from /scratch/zephyr/zp1/zephyr/arch/arm/core/offsets/offsets.c:26:
/scratch/zephyr/zp1/zephyr/include/arch/arm/cortex_m/cmsis.h:92:2: error: #error "DT_NUM_IRQ_PRIO_BITS and __NVIC_PRIO_BITS are not set to the same value"
 #error "DT_NUM_IRQ_PRIO_BITS and __NVIC_PRIO_BITS are not set to the same value"
  ^~~~~

Signed-off-by: Peter Bigot <peter.bigot@nordicsemi.no>