usb: device_next: fix building issue caused by log format string
Fix the following building issue:
usb/device_next/class/loopback.c:223:25: error: format '%zu' expects
argument of type 'size_t', but argument 3 has type 'int' [-Werror=format=]
  223 |                 LOG_WRN("Device-to-Host, wLength %u | %zu",
		  setup->wLength, len);

Fixes #113792

Signed-off-by: Jiafei Pan <Jiafei.Pan@nxp.com>