drivers: sensor: bmp581: ifdef static function
So it is only built when needed, and we avoid a compiler warning:
bmp581.c:59:19: error: unused function 'bmp581_pm_busy_check'

The issue was there since c68a25e4d531462505eaf4e9f45c1d31a311088b
but only became apparent in CI when its test was added in
f0802b645b6ad215af05adbde72ab35333834191

Signed-off-by: Alberto Escolar Piedras <alberto.escolar.piedras@nordicsemi.no>