Bluetooth: Audio: Broadcast Assistant
Added the broadcast assistant service (BASS) and sample client.
PAST is not yet supported.

Signed-off-by: Emil Gydesen <emil.gydesen@nordicsemi.no>

Bluetooth: Audio: BASS - Replace deprecated macro

Replace deprecated macro DEVICE_INIT with DEVICE_DEFINE.
See https://github.com/zephyrproject-rtos/zephyr/pull/29815

Signed-off-by: Asbjørn Sæbø <asbjorn.sabo@nordicsemi.no>

Bluetooth: Audio: Bugfix - call bass.c DEVICE_INIT with unique name

bass.c called DEVICE_INIT with the same first parameter (dev_name) as
tbs.c did.

After the rebase, this caused the build to break, due to
gen_handles.py asserting:

File
"[...]/zephyr/scripts/gen_handles.py", line 194, in main
assert len(devices) == len(handles), 'mismatch devices and handles'
AssertionError: mismatch devices and handles
ninja: build stopped: subcommand failed.

Signed-off-by: Asbjørn Sæbø <asbjorn.sabo@nordicsemi.no>