drivers: cache: nrf: Add missing checks for NRF_CACHE_HAS_LINEADDR
The _ccache_checks function only exists when NRF_CACHE_HAS_LINEADDR is
defined. This was causing compilation failures when building
the arch.interrupt.gen_isr_table_local.riscv test:

./scripts/twister -c -s arch.interrupt.gen_isr_table_local.riscv --all

drivers/cache/cache_nrf.c: In function 'cache_data_flush_and_invd_range':
drivers/cache/cache_nrf.c:272:16: error: implicit declaration of
function '_cache_checks'; did you mean '_cache_all_checks'?
[-Werror=implicit-function-declaration]
 return _cache_checks(NRF_DCACHE, K_NRF_CACHE_FLUSH, addr, size, true);
        ^~~~~~~~~~~~~
        _cache_all_checks

Issue #92194

Signed-off-by: Tom Hughes <tomhughes@chromium.org>