fs: fcb: fix clang build error
Clang build fails since ea9ee3ee3a3 with:

/__w/zephyr/zephyr/subsys/fs/fcb/fcb.c:263:11: error: fields must have a
constant size: 'variable length array in structure' extension will never
be supported

Replace the union with a buffer and pointer.

Signed-off-by: Fabio Baltieri <fabiobaltieri@google.com>