usb: host: add missing const qualifier
Add missing const qualifier, fix build issue found when building with
clang:

$ export ZEPHYR_TOOLCHAIN_VARIANT=llvm
$ west build -p -b native_sim/native tests/subsys/usb/device_next
...
zephyrproject/zephyr/subsys/usb/host/usbh_desc.c:16:6: error:
conflicting types for 'usbh_desc_is_valid'
   16 | bool usbh_desc_is_valid(const void *const desc,
      |      ^
zephyrproject/zephyr/subsys/usb/host/usbh_desc.h:92:12:
note: previous declaration is here
   92 | const bool usbh_desc_is_valid(const void *const desc,
      |            ^

Signed-off-by: Fabio Baltieri <fabiobaltieri@google.com>