soc: st: common: stm32cube_hal: add assertions glue for HAL2
The STM32Cube HAL2 uses different hooks for assertion failures.
Attempting to enable HAL assertions on series using HAL2 right now
results in a build failure because we don't provide these hooks.

For example:
  west build samples/net/dhcpv4_client/ -b nucleo_c5a3zg
  -DCONFIG_ASSERT=y -DCONFIG_USE_STM32_ASSERT=y -p

results in the following messages (shortened for clarity):
  [293/298] Linking C executable zephyr/zephyr_pre0.elf
  FAILED: zephyr/zephyr_pre0.elf zephyr/zephyr_pre0.map
  ld.bfd: in function `HAL_RCC_PSI_GetConfig':
  .../stm32c5xx/drivers/hal/stm32c5xx_hal_rcc.c:1596:
       undefined reference to `assert_dbg_param_failed'
  ld.bfd: in function `HAL_ETH_SetConfig':
  .../stm32c5xx/drivers/hal/stm32c5xx_hal_eth.c:1465:
       undefined reference to `assert_dbg_state_failed'

Add glue code needed for compatibility with HAL2 and, while at it, also
clean up the HAL1-specific hook.

Signed-off-by: Mathieu Choplain <mathieu.choplain-ext@st.com>