tests: net: lib: http_server: Disable erroneous warning from clang
The warning emitted is:

tests/net/lib/http_server/core/src/main.c:1400:19: error: variable
'http1_header_capture_common_response' is not needed and will not be
emitted [-Werror,-Wunneeded-internal-declaration]
static const char http1_header_capture_common_response[]
                  ^                             = "HTTP/1.1 200\r\n"

However, this variable is needed at compile-time since it's referenced
via sizeof(). This appears to be the same as this clang bug:
https://github.com/llvm/llvm-project/issues/25458.

This warning only started being emitted when I re-enabled the
-Wunused-function warning for clang.

Signed-off-by: Tom Hughes <tomhughes@chromium.org>