Revert "boards: silabs: siwx91x: Expose real layout of the flash"
This reverts commit 53375e95ba150f478fa4f3d37b599964e0cdf50e.

Some boards are failing with:

OverflowError: can't convert negative int to unsigned

Signed-off-by: Anas Nashif <anas.nashif@intel.com>