MAINTAINERS.yml: Fix a few renamed directories
In the course of out development, we move directories around but the
MAINTAINERS.yml is often left behind.  It's unusable with the
non-existing paths because ./scripts/get_maintainer.py just bails out
with the following message:

     error: MAINTAINERS.yml: glob pattern 'foo/*' in 'files' in area
     'Bar' does not match any files

This commit fixes renamed directories in MAINTAINERS.yml.  We still
have some issues with it and won't be able to use the script just yet.

See #32531

Signed-off-by: Yasushi SHOJI <yashi@spacecubics.com>