boards: mimxrt*: Temporarily disable Ethernet [REVERT ME]
Many of the networking PRs are failing in these boards because
of this build error:

ERROR: section nocache is 128 bytes in the virtual/runtime address \
space, but only 0 in the loaded/XIP section!

See #16778 for details.

So temporarily disable Ethernet support so that unrelated PRs can
be merged. This should be reverted after the root cause is found
and #16778 is fixed.

Signed-off-by: Jukka Rissanen <jukka.rissanen@linux.intel.com>