drivers: eth_nxp_imx_netc: add missing netc_eth_get_ptp_clock argument
Fix build error:

eth_nxp_imx_netc.c:304: error: too few arguments to function
'netc_eth_get_ptp_clock'

Add the missing argument tested with:

west build -p -b imx943_evk/mimx94398/m33/ddr
samples/net/ethernet/tsn-switch

Signed-off-by: Fabio Baltieri <fabiobaltieri@google.com>