samples: net: Disable native_posix netusb target in samples
The native_posix netusb compilations fail with various socket
errors like this:

samples/net/sockets/echo_server/src/udp.c:45:26: error: implicit \
 declaration of function ‘socket’ [-Werror=implicit-function-declaration]
 45 |         data->udp.sock = socket(bind_addr->sa_family, SOCK_DGRAM,
    |                                 IPPROTO_UDP);

Disable the netusb support from networking samples for native_posix
board for now so that CI can pass.

Signed-off-by: Jukka Rissanen <jukka.rissanen@nordicsemi.no>