arch: arm: link libatomic for C++ on ARMv6-M targets
ARMv6-M (Cortex-M0/M0+) lacks native atomic instructions. When C++
code uses std::atomic, GCC requires libatomic to provide software
implementations of atomic operations such as __atomic_compare_exchange.

Without this, linking fails with:
  undefined reference to '__atomic_compare_exchange_4'

Link libatomic conditionally when CONFIG_CPP is enabled on
Cortex-M0/M0+ targets.

Fixes #109380

Signed-off-by: Moksh Panicker <mokshpanicker.7@gmail.com>