Revert "init: add missing initialization of dev pointer in SYS_INIT macro"
This reverts commit 2438dbb613731f1abb90be9e1b4c7bd529d46574.

This commit breaks compilation on the Cadence XCC toolchain we
use for Intel Tiger Lake products (this is the oldest platform we
support in Zephyr upstream for the audio DSP).

Error:
lib/os/p4wq.c:216: error: unknown field ‘dev’ specified in initializer
lib/os/p4wq.c:216: warning: missing braces around initializer
lib/os/p4wq.c:216: warning: (near initialization for
  ‘__init_static_init.<anonymous>’)

This is XCC RG-2017.8-linux (xt-xcc version 12.0.8)

Signed-off-by: Kai Vehmanen <kai.vehmanen@linux.intel.com>