samples: net: midi2: Fix compiler warning
When building with clang we get the following warning when building the
sample.net.midi2.host_auth_user test:

samples/net/midi2/src/main.c:122:54: error: initializer element is not a
compile-time constant
  122 | NETMIDI2_EP_DEFINE_WITH_USERS(midi_server, ump_ep_dt.name, NULL, 0,
      |                                            ~~~~~~~~~~^~~~
include/zephyr/net/midi2.h:99:12: note: expanded from macro
'NETMIDI2_EP_DEFINE_WITH_USERS'
   99 |                 .name = (_ep_name), \
      |                          ^~~~~~~~

Instead of using ump_ep_dt.name for initialization, we use the
equivalent expression that UMP_ENDPOINT_DT_SPEC_GET(DT_NODELABEL(midi2))
initializes the ".name" member with.

Signed-off-by: Tom Hughes <tomhughes@chromium.org>