drivers: entropy: disable nxp CAAM driver due to CI failures
We get failures in CI when building the CAAM driver:

hal/nxp/mcux/mcux-sdk/drivers/caam/fsl_caam.c:18:2:
error: #warning "DCACHE must be set to write-trough mode
                 to safely invalidate cache!!" [-Werror=cpp]

Disable the driver for now.

Signed-off-by: Kumar Gala <galak@kernel.org>