drivers: sensor: Fix unused function warning
Building with clang warns:

drivers/sensor/st/lis2dw12/lis2dw12.c:194:23: error: unused
function 'sensor_ms2_to_mg' [-Werror,-Wunused-function]
static inline int32_t sensor_ms2_to_mg(const struct sensor_value *ms2)
                      ^

sensor_ms2_to_mg is only called when CONFIG_LIS2DW12_SLEEP or
CONFIG_LIS2DW12_WAKEUP is defined.

Signed-off-by: Tom Hughes <tomhughes@chromium.org>