scripts: requirements-extra.txt: Add patool
The Patool library is used/required by the recently introduced "west
sdk" command.

Without this change, "west sdk install" fails with the following error:

> ModuleNotFoundError: No module named 'patoolib'

Signed-off-by: Reto Schneider <reto.schneider@husqvarnagroup.com>