usb: device: audio: Fix compiler warning
When building sample.usb.legacy.audio.headphones_microphone, clang
warns:

subsys/usb/device/class/audio/audio.c:1053:34: error: implicit
conversion from 'int' to 'int16_t' (aka 'short') changes value from
47616 to -17920 [-Werror,-Wconstant-conversion]
 1053 | LISTIFY(HEADPHONES_DEVICE_COUNT, HEADPHONES_DEVICE, (), HP)
      | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~

The constant 0xBA00 (47616) is coming from "volume-min" in
samples/subsys/usb/legacy/audio_headphones_microphone/app.overlay.

According to the documentation, volume-min and volume-max are expected
to be signed:
https://docs.zephyrproject.org/latest/build/dts/api/bindings/usb/usb-audio-feature-volume.html,
so we explicitly cast to int16_t to suppress the warning.

Signed-off-by: Tom Hughes <tomhughes@chromium.org>