drivers: display: Sitronix ST7567 avoid uninitialized build warning
gcc 14 believes this function may return an unitialized value causing
undefined behaviour in the caller:

drivers/display/display_st7567.c:415:12: error: ‘ret’ may be used
uninitialized [-Werror=maybe-uninitialized]
  415 |         if (ret < 0) {
      |            ^

Let's fix it by initializing ret which has a trivial cost.

Signed-off-by: Alberto Escolar Piedras <alberto.escolar.piedras@nordicsemi.no>