include: zephyr: arch: add missing stddef.h/stdbool.h in cache.h
Add missing inclusion of stddef.h and stdbool.h to respectively define
size_t and bool types used in some cache.h function declarations.

This change prevents build errors like:

.../include/zephyr/arch/cache.h:105:41: error: unknown type name 'size_t'
  105 | int arch_dcache_flush_range(void *addr, size_t size);
      |                                         ^~~~~~

Signed-off-by: Etienne Carriere <etienne.carriere@st.com>