Bluetooth: Mesh: Fix compile warning when CID check is disabled
Since the entire cid checking function is conditionally included based
on KConfig, the usage site also needs to use #if instead of IS_ENABLED,
otherwise you get the following warning during compilation when the
option is disabled:

`error: implicit declaration of function
‘bt_mesh_vnd_mod_msg_cid_check’`

Signed-off-by: Ludvig Jordet <ludvig.jordet@nordicsemi.no>