logging: Avoid compile error if debug prints are disabled
If user has set this in .c file:

  #define LOG_MODULE_NAME abc
  #define LOG_LEVEL 0

  #include <logging/log.h>
  LOG_MODULE_REGISTER();

Here debug level is set to 0 which means that debug prints
are disabled. Then this compile error will be emitted:

  include/logging/log_instance.h:83:47: error: ‘log_dynamic_abc’
    undeclared (first use in this function);
    did you mean ‘log_dynamic_xyz’?

The commit avoids this by setting debug macros to be no-op.

Signed-off-by: Jukka Rissanen <jukka.rissanen@linux.intel.com>