Revert "boards: silabs: siwx91x: Expose real layout of the flash"
This reverts commit c631a042fdd4b4bbddea25bd9859c5e82e9b15a2.

Some boards are failing with:

OverflowError: can't convert negative int to unsigned

Signed-off-by: Anas Nashif <anas.nashif@intel.com>