drivers: dp: fix build on M0 MCUs
Current code does not build on Cortex-M0, seems like it does not like
subs:

Error: instruction not supported in Thumb16 mode -- `subs r3,#1'

Replace the instruction with a sub and cmp, add an M0+ board so this is
tested in CI.

Signed-off-by: Fabio Baltieri <fabiobaltieri@google.com>