drivers: flash: mark unused argument
Fixes:

```
zephyr/include/zephyr/drivers/flash.h:113:63: error:
unused parameter ‘p’ [-Werror=unused-parameter]
  113 | int flash_params_get_erase_cap(const struct flash_parameters *p)
      |                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
```

Signed-off-by: Vasilii Aleksandrov <vasilii.aleksandrov@gmail.com>