drivers: gpio: pca95xx: Remove unused function
Building with clang warns:

drivers/gpio/gpio_pca95xx.c:256:19: error: unused function
'update_input_reg' [-Werror,-Wunused-function]
static inline int update_input_reg(const struct device *dev, uint8_t pin,
                  ^

Signed-off-by: Tom Hughes <tomhughes@chromium.org>