tests: drivers: build_all: ethernet: Configure kernel heap
4b0c39eaaf756f added netif:eth support for a number of boards. For at
least a few of these, the net.ethernet.build.default test fails to build
due to an undefined reference to k_aligned_alloc which, in turn, is
caused by K_HEAP_MEM_POOL_SIZE being 0. Configure the kernel heap size
to emit the aforementioned symbol.

Signed-off-by: Vilhelm Engström <vilhelm.engstrom@tuta.io>