native_simulator: include folder for missing asm/errno.h
On an x86_64 Ubuntu host, the following command would result in an error.

```shell
west build -p -b native_sim/native tests/net/wifi/configs \
  -T wifi.build.hostapd_ap
...
In file included from /usr/include/bits/errno.h:26,
                 from /usr/include/errno.h:28,
                 from ~/zephyrproject/zephyr/scripts/native_simulator/\
                   /common/src/nce.c:24:
/usr/include/linux/errno.h:1:10: fatal error: asm/errno.h: \
  No such file or directory
    1 | #include <asm/errno.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
```

Include `/usr/include/x86_64-linux-gnu` in the search path so that the
build succeeds.

Signed-off-by: Chris Friedt <cfriedt@tenstorrent.com>