modules: opentread: platform: inclusion of assert.h header to udp.c
This commit add assert.h header file to avoid compilation warning due to
imnplicit declaration of function assert and respective linking related
error: undefined reference to 'assert'

Signed-off-by: Marcio Ribeiro <marcio.ribeiro@espressif.com>