tests/lib/cpp/cxx: add failing test case
This test case is meant to test the use of preprocessor macros that
paste together a number from devicetree with a suffix, like UINT32_C.
The test case is expected to fail because the C++ preprocessor does not
elide comments added by gen_dts_defines.py before expanding the macros,
resulting in errors like the following:

  error: pasting "/* 0x2 */" and "U" does not give
         a valid preprocessing token

or, in this synthetic test case:

  error: unable to find numeric literal operator 'operator""UU'

when accessing values from the devicetree_generated.h header file.

Signed-off-by: Luca Burelli <l.burelli@arduino.cc>