arch/arm: remove anonymous struct from struct _thread_arch
When CONFIG_ARM_STORE_EXC_RETURN or CONFIG_USERSPACE were enabled,
then _thread_arch contained anonymous struct, which is not allowed
by C++ standard. GCC generates a warning about this when using pedantic
flag:

error: ISO C++ prohibits anonymous structs [-Werror=pedantic]

thread.h get included by zephyr/kernel.h. Avoiding to include it on C++
application might be hard.

Fix this by giving the name to the struct.

Signed-off-by: Miika Karanki <miika.karanki@vaisala.com>