arch: Correct ARM platform Flash options.
The flash related options are required when build RAM based
binary on ARM platform.

Fixed below build issue:

configs.c: In function '_ConfigAbsSyms':
configs.c:24:136: error: expected expression before ')' token
 GEN_ABSOLUTE_SYM(CONFIG_FLASH_SIZE, );
configs.c:25:160: error: invalid suffix "x" on integer constant
GEN_ABSOLUTE_SYM(CONFIG_FLASH_BASE_ADDRESS, 0x);

Signed-off-by: Dong Xiang <dong.xiang@unisoc.com>