net: pkt: Remove unused function
Building with clang warns:

subsys/net/ip/net_pkt.c:496:34: error: unused function 'get_tx_slab'
[-Werror,-Wunused-function]
static inline struct k_mem_slab *get_tx_slab(struct net_context *context)
                                 ^

Signed-off-by: Tom Hughes <tomhughes@chromium.org>