MAINTAINERS: fix missing ":"
Add a missing ":" for "Drivers: Regulators", currently causing PR
assigner failure:

```
yaml.scanner.ScannerError: while scanning a simple key
  in "MAINTAINERS.yml", line 976, column 1
could not find expected ':'
  in "MAINTAINERS.yml", line 977, column 3
```

Signed-off-by: Fabio Baltieri <fabiobaltieri@google.com>