logging: Fix compilation errors with clang++ when printing void*
Arguments logged with %p casted to void * are working fine with gcc, g++ and
clang. however with clang++ it causes compilation error that cannot be
suppressed: error: arithmetic on a pointer to void.

Link: https://docs.zephyrproject.org/latest/services/logging/index.html#recommendations
Link: https://gcc.gnu.org/legacy-ml/gcc/2016-02/msg00266.html

Fixes: #87308

Signed-off-by: Maciej Kusio <rysiof@gmail.com>