Bluetooth: audio: lc3: Fix build error
This fixes build error caused by redundant comma without expression
lc3.h:269:74: error: expected expression before ',' token
  269 |          (_max_frames_per_sdu)))),                         \
      |

Signed-off-by: Mariusz Skamra <mariusz.skamra@codecoup.pl>