include: can: Always provide z_impl_can_recover()
Where the CAN API tests were configured with

CONFIG_CAN_MANUAL_RECOVERY_MODE = n

the tests did not link due to:

classic.c:1351: undefined reference to `z_impl_can_recover'
classic.c:1128: undefined reference to `z_impl_can_recover'
classic.c:1142: undefined reference to `z_impl_can_recover'

Fix this by always providing a z_impl_can_recover() implementation.

Signed-off-by: Sebastian Huber <sebastian.huber@embedded-brains.de>