arch: common: Fixed compile error with multi interrupt.
When enable 2-level interrupt with CONFIG_MULTI_LEVEL_INTERRUPTS
and CONFIG_2ND_LEVEL_INTERRUPTS, it will cause below issue:

  [ 97%] Generating isr_tables.c
    File "zephyr/arch/common/gen_isr_tables.py", line 199
       if syms["CONFIG_3RD_LEVEL_INTERRUPTS"]:
                                            ^
   TabError: inconsistent use of tabs and spaces in indentation
   *** [zephyr/isr_tables.c] Error 1

Signed-off-by: Dong Xiang <dong.xiang@unisoc.com>