manifest: update hal_espressif for missing source
Adds the missing SPI sources on the C5, C6 and H2 ports.

Without this fix, any image that pulls in the SPI master driver
fails to link with:

  undefined reference to 'spi_periph_signal'

The following build_all targets are restored by the bump:

  tests/drivers/build_all/eeprom on esp32c5_devkitc
  tests/drivers/build_all/gpio   on esp32c6_devkitc
  tests/drivers/spi/spi_loopback on esp32h2_devkitm

Signed-off-by: Sylvio Alves <sylvio.alves@espressif.com>