soc: arm: stm32h7: remove HAS_SWO
The only thing that uses HAS_SWO at the moment is
CONFIG_LOG_BACKEND_SWO. When that is set, stm32h7
based boards are failing to run logging sample with
compilation error:

 error: implicit declaration of function 'LL_DBGMCU_SetTracePinAssignment'

So disable SWO for now to allow building the sample
through twister for the boards that support that.

Signed-off-by: Miika Karanki <miika.karanki@vaisala.com>