samples: bbc_microbit: pong: Include hci.h, for BT_LE_ADV_IND
bluetooth/hci.h #defines BT_LE_ADV_IND. Since commit e53ee2d
("Bluetooth: Host: Move HCI error codes to its own header"), it is no
longer indirectly included via bluetooth/conn.h.

Include bluetooth/hci.h explicitly. This fixes this compilation error:

    error: 'BT_LE_ADV_IND' undeclared (first use in this function); did
    you mean 'BT_LE_ADV_CONN'?

      if (type != BT_LE_ADV_IND) {
                  ^~~~~~~~~~~~~
                  BT_LE_ADV_CONN

Signed-off-by: Ulf Magnusson <Ulf.Magnusson@nordicsemi.no>