test: timer: Fix symbol conflict
Timer test fail to build with the error below:

    .../tick_timer_train.c:12: error: "TIMERS" redefined [-Werror]
       12 | #define TIMERS 4
          |
    In file included from .../zephyr/soc/.../siwg917/soc.h:8,
                     from .../modules/cmsis_6/cmsis_core_m.h:24,
                     from .../modules/cmsis_6/cmsis_core.h:10,
                     from .../zephyr/include/.../asm_inline_gcc.h:24,
                     from .../zephyr/include/.../asm_inline.h:18,
                     from .../zephyr/include/.../arch.h:30,
                     from .../zephyr/include/.../cpu.h:19,
                     from .../zephyr/include/.../kernel_includes.h:36,
                     from .../zephyr/include/.../kernel.h:17,
                     from .../zephyr/tests/.../tick_timer_train.c:7:
    .../modules/hal/silabs/wiseconnect/components/.../si91x_device.h:15930:
                     note: this is the location of the previous definition

Indeed, the CMSIS interface of Silabs siwx91x also defines "TIMERS" symbol.
"TIMERS" is a common names in the CMSIS interfaces. So, it makes sense to
avoid to redefine it in the applications.

Signed-off-by: Jérôme Pouiller <jerome.pouiller@silabs.com>