authenticaion: fido2: fix k_thread_name_set argument
Fix k_thread_name_set argument to use thread_id as thread is deprecated.
Fixes build warning in CI:

subsys/authentication/fido2/transport/fido2_transport_usb_hid.c:548:9:
error: 'thread' is deprecated [-Werror=deprecated-declarations]

Signed-off-by: Fabio Baltieri <fabiobaltieri@google.com>