cmake: armlink: fix No Load Execution Region error
Add system symbols in right region (FLASH) instead of the first
non-empty load section to fix below build errors:

```
Error: L6384E: No Load Execution Region of name ramfunc seen yet at line
11.
Error: L6384E: No Load Execution Region of name bss seen yet at line 13.
Error: L6384E: No Load Execution Region of name bss seen yet at line 17.
```

Signed-off-by: Sudan Landge <sudan.landge@arm.com>