test: lib: c_lib: do not define standard functions as static
Define local implementations as weak instead of static.

This avoids the following error under certain conditions.

error: static declaration of 'isinff' follows non-static declaration
   64 | static int isinff(float x)
      |            ^~~~~~
note: previous declaration of 'isinff' with type 'int(float)'
  121 | extern int isinff (float);
      |            ^~~~~~
error: static declaration of 'isnanf' follows non-static declaration
   75 | static int isnanf(float x)
      |            ^~~~~~
note: previous declaration of 'isnanf' with type 'int(float)'
  122 | extern int isnanf (float);
      |            ^~~~~~

Signed-off-by: Christopher Friedt <cfriedt@meta.com>