[nrf fromlist] net: posix: Avoid multiple definitions of IFNAMSIZ symbol
One might see this compile error depending on what order the
POSIX headers are included

include/zephyr/net/net_compat.h:143: error: "IFNAMSIZ" redefined
.../zephyr/include/zephyr/net/net_compat.h:143:
                                error: "IFNAMSIZ" redefined [-Werror]
  143 | #define IFNAMSIZ NET_IFNAMSIZ
      |
In file included from ...
.../zephyr/include/zephyr/posix/net/if.h:16:
                note: this is the location of the previous definition
   16 | #define IFNAMSIZ IF_NAMESIZE
      |

Upstream PR #: 102622

Signed-off-by: Jukka Rissanen <jukka.rissanen@nordicsemi.no>
Signed-off-by: Tomasz Moń <tomasz.mon@nordicsemi.no>
(cherry picked from commit d373b7dfa2ff013793bd37837616108a29c40250)