soc: silabs_exx32: define an empty pm_state_exit_post_ops
Some EFR32 build broke after f2cba68dc9 with:

pm.c:152: undefined reference to `pm_state_exit_post_ops'

Add an extra empty function to make this one build again.

Signed-off-by: Fabio Baltieri <fabiobaltieri@google.com>