tests: net: Use ARG_UNUSED instead of self assignment
When building with clang it warns about self-assignment in these tests:

* net.icmpv6
* net.shell
* net.arp
* net.tcp
* net.ip_addr
* net.6lo
* net.icmpv4
* net.udp

Example:

error: explicitly assigning value of variable of type
'struct net_udp_context *' to itself [-Werror,-Wself-assign]

Signed-off-by: Tom Hughes <tomhughes@chromium.org>